// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxhoxKno6k0DSfhAXaxPm11_XjjKp0qYY',
    appId: '1:289837798399:web:1068cd5d3789070d680dca',
    messagingSenderId: '289837798399',
    projectId: 'bsdealz-4b71c',
    authDomain: 'bsdealz-4b71c.firebaseapp.com',
    storageBucket: 'bsdealz-4b71c.appspot.com',
    measurementId: 'G-2F7NX52ZM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrBB4cIrZpmUPhowIn0TVo5CHilJ2J2PQ',
    appId: '1:289837798399:android:40f909c4f6ab37ba680dca',
    messagingSenderId: '289837798399',
    projectId: 'bsdealz-4b71c',
    storageBucket: 'bsdealz-4b71c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByiJeyQEjgq8TfzQEGjXzMkRbHt4jXn88',
    appId: '1:289837798399:ios:db6f7b34911f3958680dca',
    messagingSenderId: '289837798399',
    projectId: 'bsdealz-4b71c',
    storageBucket: 'bsdealz-4b71c.appspot.com',
    androidClientId: '289837798399-7kbernr052iv8pbgknascognu6uosnf5.apps.googleusercontent.com',
    iosClientId: '289837798399-c92ordrorri3bpn7nr05uqu01uhsai04.apps.googleusercontent.com',
    iosBundleId: 'com.qtechnetworks.bsdealz.bsdealz',
  );
}
